language: r
sudo: false
cache: 
  packages: true
  directories:
    - _bookdown_files

addons:
   apt:
     packages:
       - libgsl0-dev # for topicmodels
       - libxml2-dev # for XML, a dependency of quanteda
       - xorg openbox

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'