language: r
sudo: false
cache: 
  packages: true
  directories:
    - _bookdown_files

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: aaf9069aaea443ff1d6facc5ddafc3ed0437b66d #$GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  fqdn: https://mystifying-khorana-d80ecb.netlify.com/ #travis-blogdown.yihui.name